# Generated by Django 3.2.8 on 2021-11-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rir_data', '0005_auto_20211118_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvester_class', models.CharField(choices=[('rir_harvester.harveters.api_with_geography_and_date.APIWithGeographyAndDate', 'API With Geography And Date')], help_text='The type of harvester that will be used.Use class with full package.', max_length=256)),
                ('is_run', models.BooleanField(default=False, help_text='Is the harvester running.')),
                ('active', models.BooleanField(default=True, help_text='Make this harvester ready to be harvested.')),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rir_data.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='This is when the harvester is started.')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Error', 'Error'), ('Done', 'Done')], default='Running', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_harvester.harvester')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='HarvesterMappingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_value', models.CharField(help_text='The original value from remote', max_length=512)),
                ('platform_value', models.CharField(help_text='The platform value', max_length=512)),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_harvester.harvester')),
            ],
            options={
                'unique_together': {('harvester', 'remote_value')},
            },
        ),
        migrations.CreateModel(
            name='HarvesterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of attribute', max_length=256)),
                ('value', models.CharField(blank=True, help_text='The value of attribute', max_length=512, null=True)),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_harvester.harvester')),
            ],
            options={
                'unique_together': {('harvester', 'name')},
            },
        ),
    ]
