# Generated by Django 3.2.8 on 2021-10-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='', max_length=512)),
                ('primary_color', models.CharField(blank=True, default='#45ABE1', help_text='Put the hex color with # (e.g. #ffffff) or put the text of color. (e.g. blue)', max_length=16, null=True)),
                ('secondary_color', models.CharField(blank=True, default='#E34E09', help_text='Put the hex color with # (e.g. #ffffff) or put the text of color. (e.g. blue)', max_length=16, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='settings/icons')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='settings/icons')),
            ],
            options={
                'verbose_name_plural': 'site preferences',
            },
        ),
    ]
