# Generated by Django 3.2.8 on 2021-11-03 05:48

from django.db import migrations, models
import rir_data.models.geometry


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='active_date_from',
            field=models.DateField(default=rir_data.models.geometry.default_active_date_from),
        ),
        migrations.AddField(
            model_name='geometry',
            name='active_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
