# Generated by Django 3.2.8 on 2021-11-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0002_auto_20211104_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='indicator',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
