# Generated by Django 3.2.8 on 2021-11-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0004_auto_20211116_0637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvesterattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='harvesterattribute',
            name='harvester',
        ),
        migrations.RemoveField(
            model_name='harvesterlog',
            name='harvester',
        ),
        migrations.DeleteModel(
            name='Harvester',
        ),
        migrations.DeleteModel(
            name='HarvesterAttribute',
        ),
        migrations.DeleteModel(
            name='HarvesterLog',
        ),
    ]
