# Generated by Django 3.2.8 on 2021-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rir_data', '0005_auto_20211118_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='show_in_traffic_light',
            new_name='show_in_context_analysis',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='show_in_context_analysis',
            field=models.BooleanField(default=True, help_text='Showing this indicator on Context Analysis.'),
        ),
    ]
