# Generated by Django 3.2.8 on 2021-11-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0006_auto_20211124_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextLayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ContextLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=256)),
                ('url_legend', models.CharField(blank=True, max_length=256, null=True)),
                ('layer_type', models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Raster Tile', 'Raster Tile')], default='ARCGIS', max_length=256)),
                ('show_on_map', models.BooleanField(default=True)),
                ('enable_by_default', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, help_text='Token to access the layer', max_length=512, null=True)),
                ('username', models.CharField(blank=True, help_text='Username to access the layer', max_length=512, null=True)),
                ('password', models.CharField(blank=True, help_text='Password to access the layer', max_length=512, null=True)),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rir_data.contextlayergroup')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_data.instance')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ContextLayerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of parameter', max_length=128)),
                ('value', models.CharField(blank=True, help_text='The value of parameter', max_length=128, null=True)),
                ('context_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_data.contextlayer')),
            ],
            options={
                'unique_together': {('context_layer', 'name')},
            },
        ),
    ]
