# Generated by Django 3.2.8 on 2021-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0007_contextlayer_contextlayergroup_contextlayerparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorscenariorule',
            name='color',
            field=models.CharField(blank=True, help_text='Color that override the scenario level color', max_length=16, null=True),
        ),
    ]
