# Generated by Django 3.2.8 on 2021-12-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0008_indicatorscenariorule_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextlayergroup',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='ContextLayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of style', max_length=128)),
                ('value', models.CharField(blank=True, help_text='The value of style', max_length=1024, null=True)),
                ('icon', models.FileField(blank=True, help_text='The icon of the style', null=True, upload_to='')),
                ('context_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_data.contextlayer')),
            ],
            options={
                'unique_together': {('context_layer', 'name')},
            },
        ),
    ]
