# Generated by Django 3.2.8 on 2021-12-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0009_auto_20211206_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons')),
                ('white_icon', models.FileField(blank=True, null=True, upload_to='icons')),
                ('url', models.CharField(max_length=256)),
                ('show_on_map', models.BooleanField(default=True)),
                ('enable_by_default', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_data.instance')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BasemapLayerParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of parameter', max_length=128)),
                ('value', models.CharField(blank=True, help_text='The value of parameter', max_length=128, null=True)),
                ('basemap_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rir_data.basemaplayer')),
            ],
            options={
                'unique_together': {('basemap_layer', 'name')},
            },
        ),
    ]
