# Generated by Django 3.2.8 on 2021-12-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0010_basemaplayer_basemaplayerparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaplayer',
            name='type',
            field=models.CharField(choices=[('XYZ Tile', 'XYZ Tile'), ('WMS', 'WMS')], default='XYZ Tile', max_length=256),
        ),
    ]
