# Generated by Django 3.2.8 on 2022-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0013_auto_20220104_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='max_value',
            field=models.FloatField(default=100, help_text='Maximum value for the indicator that can received'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='min_value',
            field=models.FloatField(default=0, help_text='Minimum value for the indicator that can received'),
        ),
    ]
