# Generated by Django 3.2.8 on 2022-01-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0014_auto_20220105_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemaplayer',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='Make this empty to be used by every instance.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rir_data.instance'),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='Make this empty to be used by every instance.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rir_data.instance'),
        ),
    ]
