# Generated by Django 3.2.8 on 2022-01-07 01:43

from django.db import migrations, models
import rir_data.models.geometry_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0016_auto_20220106_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometryuploaderfile',
            name='file',
            field=models.FileField(upload_to=rir_data.models.geometry_uploader.upload_to),
        ),
    ]
