# Generated by Django 3.2.8 on 2022-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0017_alter_geometryuploaderfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='aggregation_method',
            field=models.CharField(choices=[('Aggregate data by average data in the levels.', 'Aggregate data by average data in the levels.'), ('Aggregate data by majority data in the levels.', 'Aggregate data by majority data in the levels.')], default='Aggregate data by average data in the levels.', max_length=256),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
