# Generated by Django 3.2.8 on 2022-01-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0018_auto_20220114_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='shortcode',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
