# Generated by Django 3.2.8 on 2022-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0019_indicator_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='dashboard_link',
            field=models.CharField(blank=True, help_text='Dashboard link of the indicator.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='indicatorgroup',
            name='dashboard_link',
            field=models.CharField(blank=True, help_text='Dashboard link of the indicator group.', max_length=1024, null=True),
        ),
    ]
