# Generated by Django 3.2.8 on 2022-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0022_auto_20220126_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='api_exposed',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='api_note',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='api_token',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='aggregation_behaviour',
            field=models.CharField(choices=[('Use all available populated geography in current time window', 'Current time window only'), ('Most recent for each geography', 'Most recent for each geography')], default='Most recent for each geography', max_length=256),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='aggregation_method',
            field=models.CharField(choices=[('Aggregate data by average data in the levels.', 'Aggregate data by average data in the levels'), ('Aggregate data by majority data in the levels.', 'Aggregate data by majority data in the levels')], default='Aggregate data by average data in the levels.', max_length=256),
        ),
    ]
