# Generated by Django 3.2.8 on 2022-01-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0023_auto_20220127_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='dashboard_link',
            field=models.CharField(blank=True, default='', help_text='A dashboard link can be any URL to e.g. a BI platform or another web site. This is optional, and when populated, a special icon will be shown next to the indicator which, when clicked, will open up this URL in a frame over the main map area.', max_length=1024, null=True),
        ),
    ]
