# Generated by Django 3.2.8 on 2022-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0025_indicator_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Accessed in public.'), ('Signin', 'Need login to access.'), ('Admin', 'Need admin level to access it.')], default='Public', max_length=126),
        ),
    ]
