# Generated by Django 3.2.8 on 2022-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0028_alter_indicator_aggregation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='aggregation_method',
            field=models.CharField(choices=[('Aggregate data by average data in the levels.', 'Aggregate data by average data in the levels'), ('Aggregate data by majority data in the levels.', 'Aggregate data by majority data in the levels'), ('Aggregate data by sum all data.', 'Aggregate data by sum of all data in the levels')], default='Aggregate data by average data in the levels.', max_length=256),
        ),
    ]
