# Generated by Django 3.2.8 on 2022-03-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0029_alter_indicator_aggregation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
