# Generated by Django 3.2.8 on 2022-03-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0030_alter_contextlayer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(help_text="Can put full url with parameters and system will use that. Or system will use 'CONTEXT LAYER PARAMETERS' if there is no parameters on the url.", max_length=512),
        ),
    ]
