# Generated by Django 3.2.8 on 2022-04-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0032_auto_20220414_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancecategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'instance categories'},
        ),
    ]
