# Generated by Django 3.2.8 on 2022-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rir_data', '0034_alter_contextlayer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorscenariorule',
            name='outline_color',
            field=models.CharField(default='#FFFFFF', help_text='Color for the outline of geometry on map.', max_length=16),
        ),
    ]
